spring.application.name=demo
# Configuração da Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mentoria
spring.datasource.username=postgres
spring.datasource.password=admin

# Configuração do Hibernate / JPA (Para criar/atualizar as tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true